--
-------------------------------------------------------------------------------------------
-- Copyright © 2010-2011, Xilinx, Inc.
-- This file contains confidential and proprietary information of Xilinx, Inc. and is
-- protected under U.S. and international copyright and other intellectual property laws.
-------------------------------------------------------------------------------------------
--
-- Disclaimer:
-- This disclaimer is not a license and does not grant any rights to the materials
-- distributed herewith. Except as otherwise provided in a valid license issued to
-- you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
-- MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
-- DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
-- INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
-- OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
-- (whether in contract or tort, including negligence, or under any other theory
-- of liability) for any loss or damage of any kind or nature related to, arising
-- under or in connection with these materials, including for any direct, or any
-- indirect, special, incidental, or consequential loss or damage (including loss
-- of data, profits, goodwill, or any type of loss or damage suffered as a result
-- of any action brought by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the possibility of the same.
--
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-safe, or for use in any
-- application requiring fail-safe performance, such as life-support or safety
-- devices or systems, Class III medical devices, nuclear facilities, applications
-- related to the deployment of airbags, or any other applications that could lead
-- to death, personal injury, or severe property or environmental damage
-- (individually and collectively, "Critical Applications"). Customer assumes the
-- sole risk and liability of any use of Xilinx products in Critical Applications,
-- subject only to applicable laws and regulations governing limitations on product
-- liability.
--
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
--
-------------------------------------------------------------------------------------------
--
--
-- Production definition of a 1K program for KCPSM6 in a Spartan-6 device using a 
-- RAMB18WER primitive.
--
-- Note: The complete 12-bit address bus is connected to KCPSM6 to facilitate future code 
--       expansion with minimum changes being required to the hardware description. 
--       Only the lower 10-bits of the address are actually used for the 1K address range
--       000 to 3FF hex.  
--
-- Program defined by 'C:\Users\equack\Documents\Xilinx\DVI-1080p\dvid_test_hd\PicoBlaze\ps2_interpreter.psm'.
--
-- Generated by KCPSM6 Assembler: 21 Apr 2017 - 15:15:59. 
--
-- Standard IEEE libraries
--
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
--
-- The Unisim Library is used to define Xilinx primitives. It is also used during
-- simulation. The source can be viewed at %XILINX%\vhdl\src\unisims\unisim_VCOMP.vhd
--  
library unisim;
use unisim.vcomponents.all;
--
--
entity ps2_interpreter is
    Port (      address : in std_logic_vector(11 downto 0);
            instruction : out std_logic_vector(17 downto 0);
                 enable : in std_logic;
                    clk : in std_logic);
    end ps2_interpreter;
--
architecture low_level_definition of ps2_interpreter is
--
signal  address_a : std_logic_vector(13 downto 0);
signal  data_in_a : std_logic_vector(35 downto 0);
signal data_out_a : std_logic_vector(35 downto 0);
signal  address_b : std_logic_vector(13 downto 0);
signal  data_in_b : std_logic_vector(35 downto 0);
signal data_out_b : std_logic_vector(35 downto 0);
signal   enable_b : std_logic;
signal      clk_b : std_logic;
signal       we_b : std_logic_vector(3 downto 0);
--
begin
--
  address_a <= address(9 downto 0) & "0000";
  instruction <= data_out_a(33 downto 32) & data_out_a(15 downto 0);
  data_in_a <= "0000000000000000000000000000000000" & address(11 downto 10);
  --
  address_b <= "00000000000000";
  data_in_b <= "00" & data_out_b(33 downto 32) & "0000000000000000" & data_out_b(15 downto 0);
   enable_b <= '0';
       we_b <= "0000";
      clk_b <= '0';
  --
  --
  -- 
  kcpsm6_rom: RAMB16BWER
  generic map ( DATA_WIDTH_A => 18,
                DOA_REG => 0,
                EN_RSTRAM_A => FALSE,
                INIT_A => X"000000000",
                RST_PRIORITY_A => "CE",
                SRVAL_A => X"000000000",
                WRITE_MODE_A => "WRITE_FIRST",
                DATA_WIDTH_B => 18,
                DOB_REG => 0,
                EN_RSTRAM_B => FALSE,
                INIT_B => X"000000000",
                RST_PRIORITY_B => "CE",
                SRVAL_B => X"000000000",
                WRITE_MODE_B => "WRITE_FIRST",
                RSTTYPE => "SYNC",
                INIT_FILE => "NONE",
                SIM_COLLISION_CHECK => "ALL",
                SIM_DEVICE => "SPARTAN6",
                INIT_00 => X"6014D412202ED70194065000D401940720060008039AD00BF03010001C401700",
                INIT_01 => X"2024D780202C37BF601ED414201ED780202C37FB6018D459202C37FD602CD780",
                INIT_02 => X"6032D4E05000377E202C37F7602CD411202C37DF6028D414202C37EF602CD411",
                INIT_03 => X"604CD71802D2159E6060D47E50005701603AD4F050005C046036D4E150005780",
                INIT_04 => X"6052D7066054D76022D21513230062FBDC2002D215737C20604AD760605AD706",
                INIT_05 => X"22D2152422D21553605ED76022D215A422D215936058D70622D215D322D215F3",
                INIT_06 => X"50007C012070D706230500F702D2153002D2153403073CFB206CDC046080D477",
                INIT_07 => X"22E662ECDC407C405000D0101000207CD718500050007C026076D7182077D760",
                INIT_08 => X"500057046090D459500057025000D780608CD41222E162DCDC807C806086D458",
                INIT_09 => X"571060A2D41120A2D78050005720609BD4145000377F57406097D4142097D780",
                INIT_0A => X"00F702D2153102D21534030760B1D47C213DD7805000570860A6D4115000377F",
                INIT_0B => X"153302D21534030760C3D42F230500F702D2153202D21534030760BAD41F2305",
                INIT_0C => X"22BB150D60D0D45A230500F702D2153402D21534030760CCD43F230500F702D2",
                INIT_0D => X"15410101030760E1D475230500F702D21533030760DBD47122BB152F60D4D44A",
                INIT_0E => X"03076118D46B22D215430101030760EDD47422D215420101030760E7D47222D2",
                INIT_0F => X"B53C02D2153BF03C10301000D0011001010D22D215450101030722D215440101",
                INIT_10 => X"2111D706100022D2B53C02D2153B02D21531F03C10301000D0011001010D22D2",
                INIT_11 => X"D470230500F702D215310307611FD46C500010042117D76010022114D7181001",
                INIT_12 => X"03076134D47D230500F702D215340307612DD469230500F702D2153203076126",
                INIT_13 => X"D7062186DC405000377F230500F702D215360307613BD47A230500F702D21535",
                INIT_14 => X"D4752162D47A216ED47D215ED469216AD46C215AD471215CD4702170DC026186",
                INIT_15 => X"22BB156222BB153022BB152E21862166D4732168D4742164D46B2160D472216C",
                INIT_16 => X"22BB157522BB156B22BB157922BB156C22BB152E22BB156822BB156E22BB156A",
                INIT_17 => X"20E3D47220DDD4752136D47A2136D47D20D6D4712121D4702128D469211AD46C",
                INIT_18 => X"6192D47222D21531618ED46922D21530618AD47020F3D47320E9D47420EFD46B",
                INIT_19 => X"61A2D47422D21535619ED47322D21534619AD46B22D215336196D47A22D21532",
                INIT_1A => X"61B2D47122D2153961AED47D22D2153861AAD47522D2153761A6D46C22D21536",
                INIT_1B => X"00F702D21531030722D2155002D2154F02D2151B61BCD77E61C2D40522D2152E",
                INIT_1C => X"00F702D21531030722D2155102D2154F02D2151B61CCD77E61D2D40622D21550",
                INIT_1D => X"00F702D21531030722D2155202D2154F02D2151B61DCD77E61E2D40422D21551",
                INIT_1E => X"00F702D21531030722D2155302D2154F02D2151B61ECD77E61F2D40C22D21552",
                INIT_1F => X"02D2153103076204D40B230500F702D2153502D21531030761FBD40322D21553",
                INIT_20 => X"03076216D40A230500F702D2153802D215310307620DD483230500F702D21537",
                INIT_21 => X"D409230500F702D2153002D215320307621FD401230500F702D2153902D21531",
                INIT_22 => X"00F702D2153302D2153203076231D478230500F702D2153102D2153203076228",
                INIT_23 => X"38000940191C1803D000D47E230500F702D2153402D215320307623AD4072305",
                INIT_24 => X"22CD15406250D53222CD1521624CD53122D2155A03076248D50922A5D7064890",
                INIT_25 => X"D760155E6263D53622CD1525625CD53522CD15246258D53422CD15236254D533",
                INIT_26 => X"D53022CD1528626FD53922CD152A626BD53822CD15266267D53722CD151E22CD",
                INIT_27 => X"6282D53D22CD151F22CDD760155F627ED52D22CD157E6277D56022CD15296273",
                INIT_28 => X"6292D55D22CD157B628ED55B22CD1522628AD52722CD153A6286D53B22CD152B",
                INIT_29 => X"62BBD52F22CD153E629ED52E22CD153C629AD52C22CD157C6296D55C22CD157D",
                INIT_2A => X"D55D22CD151C62AFD55C22CD151B62ABD55B22BBD76022CD157F22CDD760153F",
                INIT_2B => X"22CDA2CDD560E2CDD57B22CD157F62BBD50822D2150062B7D53222CD151D62B3",
                INIT_2C => X"558022D2D718952022CDD70622CD952062CDD70622CADC8022CD956022C4D760",
                INIT_2D => X"D00BF0305008B030239D15400540039D155E0450E2DBD52022DBDC0102D2D59E",
                INIT_2E => X"D00BF03030EFB0305000D00BF03050405010B0305000D00BF03030F7B0305000",
                INIT_2F => X"5000D00BF0305020B0305000D00BF03030DFB0305000D00BF0305020B0305000",
                INIT_30 => X"450E450E450E450E054022D2155B02D2151B22D2157E5000D00BF03030DFB030",
                INIT_31 => X"15001500150015005000153A1507A31A950A500002D20317350F054002D20317",
                INIT_32 => X"1500150015001500150015601509150015001500150015001500150015001500",
                INIT_33 => X"156415781563150015001532157715611573157A150015001500153115711500",
                INIT_34 => X"15681562156E1500150015351572157415661576152015001500153315341565",
                INIT_35 => X"1569156B152C15001500153815371575156A156D150015001500153615791567",
                INIT_36 => X"15001527150015001500152D1570153B156C152F152E1500150015391530156F",
                INIT_37 => X"150015001500150015001500155C1500155D150D1500150015001500153D155B",
                INIT_38 => X"15351532152E1530150015001500153715341500153115001500150815001500",
                INIT_39 => X"639DD00490005000B001B0311539152A152D1533152B15001500151B15381536",
                INIT_3A => X"000000000000000000000000000000000000000000000000000000005000D501",
                INIT_3B => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3C => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3D => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3E => X"0000000000000000000000000000000000000000000000000000000000000000",
                INIT_3F => X"0000000000000000000000000000000000000000000000000000000000000000",
               INITP_00 => X"B0A328CC8CA888CD88C88C88CC8B20CCC8D8D8D8D88D8D8DC8DC8D8CDC30AA80",
               INITP_01 => X"2275A2A2B62B62B62B6A2D8D8DA88B6A22DA88B6A22DC8D8372360DC8D8CDB0D",
               INITP_02 => X"DDDDDDDD88888888888B777777777773322A2DA8B6A2DA8B6A2D9C71C222275A",
               INITP_03 => X"8B6A22D8A2888CD8A2888CD8A2888CD8A2888CD8D8D8D8D8D8D8D8D8D8D8DDDD",
               INITP_04 => X"D8C36363636363630D8D8D8D8D8D8B7250DA88B6A22DA88B6A22DA88B6A22DA8",
               INITP_05 => X"A82A0A82A0A80A82A0920DCD31C9CC9CF763636363637230D8D8D8D8D8D8D8D8",
               INITP_06 => X"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA976A0A552222A0",
               INITP_07 => X"00000000000000000000000000000000000000000000000AC2AAAAAAAAAAAAAA")
  port map(  ADDRA => address_a,
               ENA => enable,
              CLKA => clk,
               DOA => data_out_a(31 downto 0),
              DOPA => data_out_a(35 downto 32), 
               DIA => data_in_a(31 downto 0),
              DIPA => data_in_a(35 downto 32), 
               WEA => "0000",
            REGCEA => '0',
              RSTA => '0',
             ADDRB => address_b,
               ENB => enable_b,
              CLKB => clk_b,
               DOB => data_out_b(31 downto 0),
              DOPB => data_out_b(35 downto 32), 
               DIB => data_in_b(31 downto 0),
              DIPB => data_in_b(35 downto 32), 
               WEB => we_b,
            REGCEB => '0',
              RSTB => '0');
--
--
end low_level_definition;
--
------------------------------------------------------------------------------------
--
-- END OF FILE ps2_interpreter.vhd
--
------------------------------------------------------------------------------------
